---
title: "CBECS Exploration"
author: "John Grando"
date: "January 29, 2019"
output: html_document
---

```{r echo=FALSE}
library(dplyr)
library(tidyr)
library(kableExtra)
library(gridExtra)
library(grid)
library(ggplot2)
library(randomForest)
library(corrplot)
library(caret)
library(cluster)
library(factoextra)
library(e1071)
library(ggfortify)
```

```{r}
source('tree_func.R')
```


```{r}
cbecs_raw_df <- read.csv('./2012_public_use_data_aug2016.csv', 
                         header = TRUE, 
                         stringsAsFactors = FALSE)
```

```{r}
#make column categorical and replace na with -1
make_cat_w_repl <- function(x){
  as.factor(ifelse(is.na(x), as.character(-1), as.character(x)))
}

#replace nas with a specified number in a numerical column
na_repl_num <- function(x, num){
  ifelse(is.na(x), num, x)
}
```

```{r}
#Predictor population
summary(data.frame(lapply(cbecs_raw_df[,grepl('^[^Z].*USED$', colnames(cbecs_raw_df))], factor)))
```



```{r}
#Clean the raw data file

#Identify Weight columns
weight_list <- names(cbecs_raw_df[grepl('^FINAL.*', names(cbecs_raw_df), ignore.case = TRUE)])
#Identify imputation flag columns
impute_list <- names(cbecs_raw_df[grepl('^Z.*', names(cbecs_raw_df), ignore.case = TRUE)])

cbecs_trim_df <- cbecs_raw_df %>% 
  #Remove weight and imputation columns as well as IDs
  select(-one_of(weight_list), -one_of(impute_list), -PUBID) %>% 
  #Remove small buildings - not of interest and contain NAs - also remove NAs from this column implicitly
  filter(SQFT > 1000) %>% 
  #Drop month ready for occupancy in 2012, not useful
  select(-MONCON) %>% 
  #If buidling was indicated to be not cooled, then percent cooled is zero
  mutate(COOLP = ifelse(COOL==2, 0, COOL)) %>% 
  #If one of the preceding non-electrical use questions is answered as yes, then zero for percent-lit
  mutate(LTOHRP = ifelse(ELUSED==2|WKHRS==0, 0, LTOHRP)) %>% 
  #If lights are always on, then they are never of
  mutate(LTNHRP = ifelse(WKHRS==168|OPEN24==1|LTNR24==2, 0, LTNHRP)) %>% 
  ### REMOVE FOR NOW, TOO MANY NULLS ###
  select(-LTNHRP) %>% 
  #0 percent heated, heated to less than 50, No useful information.  all one response
  select(-HTLS50) %>% 
  #Update BASEMNT to have value of 0 for one-floor buildings
  mutate(BASEMNT = ifelse(NFLOOR==1,0,BASEMNT)) %>%
  #make a has-baseament encoder and make a factor
  mutate(BASEMNT_HAS = as.factor(ifelse(is.na(BASEMNT)|BASEMNT==0,0,1))) %>% 
  #if responded with no elevators or escalators then number of elevators is 0
  mutate(NELVTR = ifelse(ELEVTR==2, 0, NELVTR)) %>% 
  mutate(NESLTR = ifelse(ESCLTR==2, 0, NESLTR)) %>% 
  #if don't know or refuse then assume zero?
  mutate_at(vars(NELVTR, NESLTR), funs(na_repl_num(.,0))) %>% 
  #If only indicated that electricity is bought from local utility, then assume it is 100%
  mutate(ELLUPCT = ifelse(ELLOCUT==1 & ELNONLU==2 & ELOTSRC==2 & ELCPLT==2, 100, ELLUPCT)) %>% 
  mutate(ELLUPCT = ifelse(ELLOCUT==2 & ELNONLU==1 & ELOTSRC==2 & ELCPLT==2, 0, ELLUPCT)) %>% 
  mutate(ELLUPCT = ifelse(ELLOCUT==2 & ELNONLU==2 & ELOTSRC==1 & ELCPLT==2, 0, ELLUPCT)) %>% 
  mutate(ELLUPCT = ifelse(ELLOCUT==2 & ELNONLU==2 & ELOTSRC==2 & ELCPLT==1, 0, ELLUPCT)) %>% 
  #fix 999 flag which means 'dont know' - NA
  mutate(ELLUPCT = ifelse(ELLUPCT==999, NA, ELLUPCT)) %>% 
  ##### Remove ELLUPCT FOR NOW ####
  select(-ELLUPCT) %>% 
  #Not interested in cost
  select(-WOEXP, -WOEXPC) %>%
  #if respondent did not indicate any residential refrigerators, then it is zero
  #also, if the question didn't apply then assume zero
  mutate(RFGRSN = ifelse(is.na(RFGEQP)|RFGEQP==2|RFGRES==2, 0, RFGRES)) %>% 
  #same for compact refrigerators
  mutate(RFGCOMPN = ifelse(is.na(RFGEQP)|RFGEQP==2|RFGCOMP==2, 0, RFGCOMPN)) %>% 
  #same for walkins
  mutate(RFGWIN = ifelse(is.na(RFGEQP)|RFGEQP==2|RFGWI==2, 0, RFGWIN)) %>% 
  #same for open cases
  mutate(RFGOPN = ifelse(is.na(RFGEQP)|RFGEQP==2|RFGOP==2, 0, RFGOPN)) %>% 
  #same for closed cases
  mutate(RFGCLN = ifelse(is.na(RFGEQP)|RFGEQP==2|RFGCL==2, 0, RFGCLN)) %>% 
  #same for vending
  mutate(RFGVNN = ifelse(is.na(RFGEQP)|RFGEQP==2|RFGVEN==2, 0, RFGVNN)) %>%
  #same for ice makers
  mutate(RFGICN = ifelse(is.na(RFGEQP)|RFGEQP==2|RFGICE==2, 0, RFGICN)) %>%
  #same for large cold storage
  mutate(RFGSTP = ifelse(is.na(RFGEQP)|RFGEQP==2|RFGSTO==2, 0, RFGSTP)) %>%
  #if tv/video response was 'no', then it is zero
  mutate(TVVIDEON = ifelse(TVVIDEO==2, 0, TVVIDEON)) %>% 
  #if cash register response was 'no', then it is zero
  mutate(RGSTRN = ifelse(RGSTR==2, 0, RGSTRN)) %>% 
  #if copoer response was 'no', then it is zero
  mutate(COPIERN = ifelse(COPIER==2, 0, COPIERN)) %>% 
  #Categorical conversions with nas - If question not asked, then encode NA as -1
  mutate_at(vars(FREESTN, RENOV, OWNOCC, RDLTNF, EQGLSS, SUNGLS, ELEVTR, ESCLTR, ACT1, ACT2, ACT3, DATACNTR, DRYCL, VACANT, 
                 CUBE, CUBEC, CUBELOC, COURT, FEDFAC, FACACT, MANIND, PLANT, 
                 FACDST, FACDHW, FACDCW, FACELC, BLDPLT, GOVTYP, OWNPPR, 
                 NWNPPR, NWNOPR, WHOPPR, ANYEGY, FKTYPE, ELHT1, NGHT1, FKHT1,
                 PRHT1, STHT1, HWHT1, WOHT1, COHT1, SOHT1, OTHT1, ELHT2, NGHT2,
                 FKHT2, PRHT2, STHT2, HWHT2, WOHT2, COHT2, SOHT2, OTHT2, FURNAC,
                 PKGHT, BOILER, STHW, HTPMPH, SLFCON, OTHTEQ, BLRRAD, BLRFNCL, BLRINDC,
                 BLRAIR, BLRPKG, BLRDUCT, DHRAD, DHFNCL, DHINDC, DHWATR, DHAIR, DHPKG,
                 DHDUCT, OTSTRP, OTDUCT, OTPIU, PKGHTTYP, PKGFURN, PKGHTP, PKGCOIL, PKGPIU,
                 PKGDUCT, HPHPKG, HPHSPLT, HPHROOM, HPHMINI, HPHVRF, HPHAIR, HPHGRD, HPHDUAL, 
                 HPHWTR, HPHBKUP, SHRDNT, SHBBRD, SHPORT, SHWALL, SHFURN, SHUNIT, SHPTAC,
                 HTVCAV, HTVVAV, HTVFLR, HTVOAS, HTVDEM, HTVNON, MAINHT, NWMNHT, ELCOOL, NGCOOL,
                 FKCOOL, PRCOOL, STCOOL, HWCOOL, CWCOOL, OTCOOL, PKGCLTYP, CHLAIRCL, CHLWTRCL, CHLABSRP,
                 HTRCHLR, CHLAIR, CHLFNCL, CHLINDC, CHLBEAM, CHLPKG, CHLDUCT, DCWAIR, DCWFNCL, DCWINDC,
                 DCWBEAM, DCWPKG, DCWDUCT, HPCPKG, HPCSPLT, HPCROOM, HPCMINI, HPCVRF, HPCAIR, HPCGRD, HPCDUAL,
                 HPCWTR, CLVCAV, CLVVAV, CLVFLR, CLVOAS, CLVDEM, CLVNON, NWMNCL, RDHTNF, HWRDHT, HWRDCL, ECN, ECNTYPE,
                 MAINT, ELWATR, NGWATR, FKWATR, PRWATR, STWATR, HWWATR, WOWATR, COWATR, SOWATR, OTWATR, WTHTEQ, BOOSTWT,
                 INSTWT, ELCOOK, NGCOOK, FKCOOK, PRCOOK, STCOOK, HWCOOK, WOCOOK, COCOOK, SOCOOK, OTCOOK, ELMANU, NGMANU,
                 FKMANU, PRMANU, STMANU, HWMANU, WOMANU, COMANU, SOMANU, OTMANU, NGGENR, FKGENR, PRGENR, WOGENR, COGENR,
                 SOGENR, OTGENR, PVC, FUELCL, LRGTRB, MCROTB, ENGINE, GENUSE, COGEN, TOGRID, ELLOCUT, ELNONLU, ELOTSRC,
                 ELCPLT, NGSRC, PRAMTC, PRUNIT, WOAMT, WOSRC, SNACK, FASTFD, CAF, FDPREP, KITCHN, BREAKRM, OTFDRM, HWTRM,
                 LAUNDR, CONFSP, MEDEQP, CTSCAN, MRI, LINACC, OUTSURG, LABEQP, MCHEQP, POOL, HTPOOL, POOLSRC, STRLZR,
                 RFGRES, RFGCOMP, RFGWI, RFGOP, RFGCL, RFGVEN, RFGICE, RFGSTO, WHRECOV, WHHT2, WHWT, WHOT, 
                 MLTMON, MLTMNC, FLATC, TRNGRM, STDNRM, DCNTRSFC, WBOARDS, PRNTYP, LTNR24, FLUOR, CFLR, BULB, HALO, 
                 HID, LED, OTLT, EMCSLT, SCHED, OCSN, DIM, DAYHARV, TRIM, PLGCTRL, DRLGHT, TINT, REFL, AWN, SKYLT, 
                 COOTH, WOOTH, OTOTH, HWOTH, SOOTH, DCWLOOP, CWOTH, STOTH, DHLOOP, DHHT1, DHHT2, DHCOOL, DHCOOK, 
                 DHMANU, DHOTH, PROTH, CHLLOOP, FKOTH, BLRLOOP, NGOTH, SQFTC, WLCNS, RFCNS, RFCOOL, RFTILT, BLDSHP, 
                 GLSSPC, EQGLSS, SUNGLS, 
                 ATTIC, YRCONC, RENADD, RENRDC, RENCOS, RENINT, RENRFF, RENWLL, RENWIN, 
                 RENHVC, RENLGT, RENPLB, RENELC, RENINS, RENSAF, RENSTR, RENOTH, ONEACT, 
                 PBAPLUS, PBA, FACIL, GOVOWN, OWNTYPE, NOCCAT, OWNOCC, OWNOPR, OPEN24, 
                 OPEN24, OPNMF, OPNWE, NWKERC, HT1, HT2, COOL, WATR, COOK, MANU, CAPGEN, ELUSED,
                 NGUSED, FKUSED, PRUSED, STUSED, HWUSED, CWUSED, OTUSED, WOUSED, COUSED, SOUSED, 
                 RCAC, PKGCL, CHILLR, CHWT, HTPMPC, ACWNWL, EVAPCL, OTCLEQ, MAINCL, EMCS, RDCLNF, GENR, AMIMETER, 
                 ENRGYPLN, RFGEQP, PCTERM, PCTRMC, LAPTPC, SERVER, SERVERC, TVVIDEO, RGSTR, COPIER, FAX, LOHRPC,
                 LNHRPC, LTEXPC, PKLT, WINTYP, REGION, CENDIV, RENOV, WKHRSC, PUBCLIM),
            funs(make_cat_w_repl(.))) %>%
  #Move down the order of activities and when there is a null, fill it in with the difference of 100 - sum
  mutate(ACT1PCT = ifelse(ACT1==-1, 100, ACT1PCT)) %>% 
  mutate(ACT2PCT = ifelse(ACT2==-1, 100-ACT1PCT, ACT2PCT)) %>% 
  mutate(ACT3PCT = ifelse(ACT3==-1, 100-ACT1PCT-ACT2PCT, ACT3PCT)) %>% 
  #create additional column that catches difference
  mutate(OTHPCT = 100 - ACT1PCT - ACT2PCT - ACT3PCT) %>% 
  #per sf values to track: electricity
  mutate(ELCNSPerSf = ELCNS / SQFT) %>%
  #electricity btu
  mutate(ELBTUPerSf = ELBTU / SQFT) %>%
  #electricity heating btu
  mutate(ELHTBTUPerSf = ELHTBTU / SQFT) %>%
  #electricity cooling btu
  mutate(ELCLBTUPerSf = ELCLBTU / SQFT) %>%
  #electricity ventilation btu
  mutate(ELVNBTUPerSf = ELVNBTU / SQFT) %>%
  #electricity water heating btu
  mutate(ELWTBTUPerSf = ELWTBTU / SQFT) %>%
  #electricity lighting btu
  mutate(ELLTBTUPerSf = ELLTBTU / SQFT) %>%
  #electricity cooking btu
  mutate(ELCKBTUPerSf = ELCKBTU / SQFT) %>%
  #electricity refrigeration btu
  mutate(ELRFBTUPerSf = ELRFBTU / SQFT) %>%
  #electricity office equipment btu
  mutate(ELOFBTUPerSf = ELOFBTU / SQFT) %>%
  #electricity computing btu
  mutate(ELPCBTUPerSf = ELPCBTU / SQFT) %>%
  #electricity miscellaneous btu
  mutate(ELOTBTUPerSf = ELOTBTU / SQFT) %>%
  #natural gas ccf
  mutate(NGCNSPerSf = NGCNS / SQFT) %>%
  #natural gas BTU
  mutate(NGBTUPerSf = NGBTU / SQFT) %>%
  #natural gas heating BTU
  mutate(NGHTBTUPerSf = NGHTBTU / SQFT) %>%
  #natural gas cooling BTU
  mutate(NGCLBTUPerSf = NGCLBTU / SQFT) %>%
  #natural gas water heating BTU
  mutate(NGWTBTUPerSf = NGWTBTU / SQFT) %>%
  #natural gas cooking BTU
  mutate(NGCKBTUPerSf = NGCKBTU / SQFT) %>%
  #natural gas misc BTU
  mutate(NGOTBTUPerSf = NGOTBTU / SQFT) %>%
  #District heat thousand pounds
  mutate(DHCNSPerSf = DHCNS / SQFT) %>%
  #District heat thousand btu
  mutate(DHBTUPerSf = DHBTU / SQFT) %>% 
  #District heat heating thousand btu
  mutate(DHHTBTUPerSf = DHHTBTU / SQFT) %>% 
  #District heat cooling thousand btu
  mutate(DHCLBTUPerSf = DHCLBTU / SQFT) %>% 
  #District heat water heating thousand btu
  mutate(DHWTBTUPerSf = DHWTBTU / SQFT) %>% 
  #District heat cooking thousand btu
  mutate(DHCKBTUPerSf = DHCKBTU / SQFT) %>%
  #District heat misc thousand btu
  mutate(DHOTBTUPerSf = DHOTBTU / SQFT) %>%
  #fuel oil
  mutate(FKCNSPerSf = FKCNS / SQFT) %>%
  #Fuel oil thousand btu
  mutate(FKBTUPerSf = FKBTU / SQFT) %>%
  #Fuel oil heating thousand btu
  mutate(FKHTBTUPerSf = FKHTBTU / SQFT) %>%
  #Fuel oil cooling thousand btu
  mutate(FKCLBTUPerSf = FKCLBTU / SQFT) %>%
  #Fuel oil water heating thousand btu
  mutate(FKWTBTUPerSf = FKWTBTU / SQFT) %>%
  #Fuel oil cooking thousand btu
  mutate(FKCKBTUPerSf = FKCKBTU / SQFT) %>%
  #Fuel oil misc thousand btu
  mutate(FKOTBTUPerSf = FKOTBTU / SQFT) %>%
  #Major fuel btu
  mutate(MFBTUPerSf = MFBTU / SQFT) %>%
  #Major fuel heating btu
  mutate(MFHTBTUPerSf = MFHTBTU / SQFT) %>%
  #Major fuel cooling btu
  mutate(MFCLBTUPerSf = MFCLBTU / SQFT) %>%
  #Major fuel ventilation btu
  mutate(MFVNBTUPerSf = MFVNBTU / SQFT) %>%
  #Major fuel water heating btu
  mutate(MFWTBTUPerSf = MFWTBTU / SQFT) %>%
  #Major fuel lighting btu
  mutate(MFLTBTUPerSf = MFLTBTU / SQFT) %>%
  #Major fuel cooking btu
  mutate(MFCKBTUPerSf = MFCKBTU / SQFT) %>%
  #Major fuel refrigeration btu
  mutate(MFRFBTUPerSf = MFRFBTU / SQFT) %>%
  #Major fuel office equipment use btu
  mutate(MFOFBTUPerSf = MFOFBTU / SQFT) %>%
  #Major fuel computing use btu
  mutate(MFPCBTUPerSf = MFPCBTU / SQFT) %>%
  #Major fuel other btu
  mutate(MFOTBTUPerSf = MFOTBTU / SQFT) %>%
  #columns not interested in tracking for this study (e.g. expenditures, total usage, etc.)
  select(-ELCNS, -ELBTU, -ELHTBTU, -ELCLBTU, -ELCLBTU, -ELVNBTU, -ELWTBTU, -ELLTBTU, -ELCKBTU,
         -ELRFBTU, -ELOFBTU, -ELPCBTU, -ELOTBTU,
         -NGCNS, -NGBTU, -NGHTBTU, -NGCLBTU, -NGWTBTU, -NGCKBTU, -NGOTBTU, -FKCNS, 
         -DHBTU, -DHCNS, -DHHTBTU, -DHCLBTU, -DHWTBTU, -DHCKBTU, -DHOTBTU, 
         -FKBTU, -FKHTBTU, -FKCLBTU, -FKWTBTU, -FKCKBTU, -FKOTBTU, -MFBTU,
         -MFHTBTU, -MFCLBTU, -MFVNBTU, -MFWTBTU, -MFLTBTU, -MFCKBTU, 
         -MFRFBTU, -MFOFBTU, -MFPCBTU, -MFOTBTU,
         -ELEXP, -NGEXP, -FKEXP, -DHEXP, -MFEXP) %>% 
  #replace nas with zeroes - if question not asked or applicable then assume zero as input
  mutate_at(vars(OCCUPYP, LODOCCP, RWSEAT, PBSEAT, EDSEAT, FDSEAT, HCBED, NRSBED, LODGRM, HEATP, FURNP, PKGHP, 
                 BOILP, STHWP, HTPHP, SLFCNP, OTHTP, RCACP, PKGCP, CHILP, CHWTP, HTPCP, ACWNWP, EVAPP, OTCLP, CONFSPP,
                 XRAYN, PRNTRN, FLUORP, CFLRP, BULBP, HALOP, HIDP, LEDP, FLUORP, CFLRP, BULBP, HALOP, HIDP, LEDP, 
                 OTLTP, DAYLTP, PCTERMN, LAPTPN, SERVERN, TVVIDEON, RGSTRN, COPIERN,
                 ELCNSPerSf, ELBTUPerSf, ELHTBTUPerSf, ELCLBTUPerSf, ELVNBTUPerSf, ELWTBTUPerSf, ELLTBTUPerSf,
                 ELCKBTUPerSf, ELRFBTUPerSf, ELOFBTUPerSf, ELPCBTUPerSf, ELOTBTUPerSf, NGCNSPerSf, NGBTUPerSf, 
                 NGHTBTUPerSf, NGCLBTUPerSf, NGWTBTUPerSf, 
                 NGCKBTUPerSf, NGOTBTUPerSf, FKCNSPerSf, DHCNSPerSf, DHBTUPerSf, DHHTBTUPerSf, DHCLBTUPerSf,
                 DHWTBTUPerSf, DHCKBTUPerSf, DHOTBTUPerSf, FKBTUPerSf, FKHTBTUPerSf, FKCLBTUPerSf, FKWTBTUPerSf, 
                 FKCKBTUPerSf, FKOTBTUPerSf, MFBTUPerSf, MFHTBTUPerSf, MFCLBTUPerSf, MFVNBTUPerSf, MFWTBTUPerSf,
                 MFLTBTUPerSf, MFCKBTUPerSf, MFRFBTUPerSf, MFOFBTUPerSf, MFPCBTUPerSf, MFOTBTUPerSf), 
            funs(na_repl_num(., 0)))


#Check columsn with NAs
cbecs_trim_na_df <- stack(colSums(is.na(cbecs_trim_df))) %>% filter(values>0)
cbecs_large_na_df <- stack(colSums(is.na(cbecs_trim_df))) %>% filter(values > 1000)

#Find columns with only one factor/value and remove
no_info_columns <- colnames(cbecs_trim_df[, sapply(cbecs_trim_df, function(x) {
  ifelse(length(unique(x))<2,TRUE, FALSE)})])
#cbecs_trim_df <- cbecs_trim_df %>% select(-one_of(no_info_columns))
```

```{r}
#Get appropriate numeric columns and divide to get PerSf metrics

#Print numeric columns for inspection
#cbecs_trim_df[, unlist(lapply(cbecs_trim_df, is.numeric))]
#Create vector for columns to be transformed

PerSfVector <- c('NFLOOR', 'BASEMNT', 'NELVTR', 'NESLTR', 'RWSEAT', 'PBSEAT',
                 'EDSEAT', 'FDSEAT', 'HCBED', 'NRSBED', 'LODGRM', 'NOCC', 'NWKER',
                 'XRAYN', 'RFGRSN', 'RFGCOMPN', 'RFGWIN', 'RFGOPN', 'RFGCLN', 'RFGVNN',
                 'RFGICN', 'PCTERMN', 'LAPTPN', 'PRNTRN', 'SERVERN', 'TVVIDEON', 'RGSTRN')
per_sf_df <- cbecs_trim_df %>% select_(.dots = PerSfVector)
per_sf_df <- per_sf_df / cbecs_trim_df[,c('SQFT')]
colnames(per_sf_df) <- paste(colnames(per_sf_df), "PerSf", sep="")
cbecs_clean_df <- cbecs_trim_df %>% 
  select(names(cbecs_trim_df[!(colnames(cbecs_trim_df) %in% PerSfVector)])) %>% 
  bind_cols(per_sf_df) %>% 
  select(-SQFT)
```

```{r}
#Make list of numeric column groups
removed_response_list <- colnames(cbecs_clean_df[,!grepl('EL.*PerSf|NG.*PerSf|DH.*PerSf|FK.*PerSf|MF.*PerSf', colnames(cbecs_clean_df), ignore.case = TRUE)])
tmp_column_list <- append(removed_response_list, c('ELBTUPerSf', 'NGBTUPerSf', 'DHBTUPerSf', 'FKBTUPerSf', 'MFBTUPerSf'))
cbecs_clean_numeric_cols <- names(cbecs_clean_df[, unlist(lapply(cbecs_clean_df, is.numeric)) & colnames(cbecs_clean_df) %in% tmp_column_list])
cbecs_clean_non_numeric_cols <- names(cbecs_clean_df[, !(colnames(cbecs_clean_df) %in% cbecs_clean_numeric_cols) & colnames(cbecs_clean_df) %in% tmp_column_list])
cbecs_clean_full_column_list <- append(cbecs_clean_numeric_cols, cbecs_clean_non_numeric_cols)
cbecs_clean_df <- cbecs_clean_df[,cbecs_clean_full_column_list]

#Convert factor columns to one-hot encoders
dummy_f <- dummyVars(" ~ .", data = cbecs_clean_df)
cbecs_trans_df <- data.frame(predict(dummy_f, newdata=cbecs_clean_df))
cbecs_trans_numeric_cols <- cbecs_clean_numeric_cols
cbecs_trans_non_numeric_cols <- names(cbecs_trans_df[, !(colnames(cbecs_trans_df) %in% cbecs_trans_numeric_cols)])
cbecs_trans_full_column_list <- append(cbecs_trans_numeric_cols, cbecs_trans_non_numeric_cols)
```

#Explore data set. response variable shapes, correlations, k-means clustering, princomp, etc. to determine possibility of prediction.

```{r fig.width=6, fig.height=5}
#histograms of possible response categories
cbecs_response_df <- cbecs_trans_df %>% 
  select(ELBTUPerSf, NGBTUPerSf, DHBTUPerSf, FKBTUPerSf, MFBTUPerSf) %>% 
  gather("source", "BTU", 1:5)
p1 <- ggplot(cbecs_response_df %>% filter(source=='ELBTUPerSf' & BTU > 0), aes(x=BTU)) + 
  geom_histogram(bins = 40) + 
  ggtitle('Electric') +
  labs(x = 'BTU Per SF', y='') +
  theme(plot.title = element_text(hjust = 0.5, size=10),
        strip.text = element_text(size = 20),
        plot.background = element_rect(fill = "lightgrey"), 
        panel.background = element_rect(fill = "white"), 
        panel.grid.major.x = element_line(color = "lightgrey"), 
        panel.grid.major.y = element_line(color = "lightgrey"), 
        axis.text = element_text(size=8, color = "grey55"), 
        axis.title = element_text(size=10, color = "grey55"),
        axis.title.y = element_text(size = 0))
p2 <- ggplot(cbecs_response_df %>% filter(source=='NGBTUPerSf' & BTU > 0), aes(x=BTU)) + 
  geom_histogram(bins = 40) + 
  ggtitle('Nat. Gas') +
  labs(x = 'BTU Per SF', y='') +
  theme(plot.title = element_text(hjust = 0.5, size=10),
        strip.text = element_text(size = 20),
        plot.background = element_rect(fill = "lightgrey"), 
        panel.background = element_rect(fill = "white"), 
        panel.grid.major.x = element_line(color = "lightgrey"), 
        panel.grid.major.y = element_line(color = "lightgrey"), 
        axis.text = element_text(size=8, color = "grey55"), 
        axis.title = element_text(size=10, color = "grey55"),
        axis.title.y = element_text(size = 0))
p3 <- ggplot(cbecs_response_df %>% filter(source=='DHBTUPerSf' & BTU > 0), aes(x=BTU))+ 
  geom_histogram(bins = 40) + 
  ggtitle('District Heat') +
  labs(x = 'BTU Per SF', y='') +
  theme(plot.title = element_text(hjust = 0.5, size=10),
        strip.text = element_text(size = 20),
        plot.background = element_rect(fill = "lightgrey"), 
        panel.background = element_rect(fill = "white"), 
        panel.grid.major.x = element_line(color = "lightgrey"), 
        panel.grid.major.y = element_line(color = "lightgrey"), 
        axis.text = element_text(size=8, color = "grey55"), 
        axis.title = element_text(size=10, color = "grey55"),
        axis.title.y = element_text(size = 0))
p4 <- ggplot(cbecs_response_df %>% filter(source=='FKBTUPerSf' & BTU > 0), aes(x=BTU)) + 
  geom_histogram(bins = 40) + 
  ggtitle('Fuel Oil') +
  labs(x = 'BTU Per SF', y='') +
  theme(plot.title = element_text(hjust = 0.5, size=10),
        strip.text = element_text(size = 20),
        plot.background = element_rect(fill = "lightgrey"), 
        panel.background = element_rect(fill = "white"), 
        panel.grid.major.x = element_line(color = "lightgrey"), 
        panel.grid.major.y = element_line(color = "lightgrey"), 
        axis.text = element_text(size=8, color = "grey55"), 
        axis.title = element_text(size=10, color = "grey55"),
        axis.title.y = element_text(size = 0))
p5 <- ggplot(cbecs_response_df %>% filter(source=='MFBTUPerSf' & BTU > 0), aes(x=BTU)) + 
  geom_histogram(bins = 40) + 
  ggtitle('All Major Fuel') +
  labs(x = 'BTU Per SF', y='') +
  theme(plot.title = element_text(hjust = 0.5, size=10),
        strip.text = element_text(size = 20),
        plot.background = element_rect(fill = "lightgrey"), 
        panel.background = element_rect(fill = "white"), 
        panel.grid.major.x = element_line(color = "lightgrey"), 
        panel.grid.major.y = element_line(color = "lightgrey"), 
        axis.text = element_text(size=8, color = "grey55"), 
        axis.title = element_text(size=10, color = "grey55"),
        axis.title.y = element_text(size = 1))
lay <- rbind(
  c(1, 2),
  c(3, 4),
  c(5, 5)
)
tmp_plot <- grid.arrange(top = "Consumption By Major Fuel", 
                         p1, p2, p3, p4, p5, 
                         ncol=2,
                         layout_matrix=lay
)
ggsave('Documents/major_fuels_preliminary_analysis.png', tmp_plot)
tmp_plot
```

# Correlation plot
```{r fig.width=40}
cbecs_clean_scaled_df <- scale(
  cbecs_clean_df %>%
    select(one_of(removed_response_list)) %>% 
    select(one_of(cbecs_clean_numeric_cols)) %>% 
    select(-matches('.*USED$'))
)
correlations_df <- cor(cbecs_clean_scaled_df)
corrplot(correlations_df)
```

#k means
```{r fig.height=8}
kmeans_fit <- kmeans(cbecs_clean_scaled_df, centers=3, nstart = 25)
fviz_cluster(kmeans_fit, data=cbecs_clean_scaled_df) + 
  ggtitle('K Means Cluster Analysis') +
  theme(plot.title = element_text(hjust = 0.5, size=20),
        strip.text = element_text(size = 20),
        plot.background = element_rect(fill = "lightgrey"), 
        panel.background = element_rect(fill = "white"), 
        panel.grid.major.x = element_line(color = "lightgrey"), 
        panel.grid.major.y = element_line(color = "lightgrey"), 
        axis.text = element_text(size=10, color = "grey55"), 
        axis.title = element_text(size=14, color = "grey55"))
ggsave('Documents/k_means_preliminary.png')
ggplot(data=cbind(cbecs_clean_df, kgroup = kmeans_fit$cluster), aes(x=log(MFBTUPerSf/WKHRS), y=log(SERVERNPerSf), color=as.factor(kgroup), shape=as.factor(kgroup))) + geom_point(aes(alpha=0.4)) + facet_wrap(~factor(ifelse(RFGWINPerSf>0|RFGCLNPerSf>0|RGSTRNPerSf,1,0)), scales = 'free')

```


#PCA
```{r fig.width=8}
cbecs_pca <- prcomp(cbecs_clean_df %>%
    select(one_of(removed_response_list)) %>% 
    select(one_of(cbecs_clean_numeric_cols))%>% 
    select(-matches('.*USED$')), 
                    center = TRUE, 
                    scale. = TRUE)
screeplot(cbecs_pca, type = 'lines')
summary(cbecs_pca)
ggplot(cbecs_pca$x, aes(x=PC1, y=PC2, color=cbecs_clean_df$PBA)) + geom_point() + geom_text(aes(label=cbecs_clean_df$PBAPLUS), nudge_x = 0.5) +
  ggtitle('Principal Component Analysis - Group IDs') +
  theme(plot.title = element_text(hjust = 0.5, size=20),
        strip.text = element_text(size = 20),
        plot.background = element_rect(fill = "lightgrey"), 
        panel.background = element_rect(fill = "white"), 
        panel.grid.major.x = element_line(color = "lightgrey"), 
        panel.grid.major.y = element_line(color = "lightgrey"), 
        axis.text = element_text(size=10, color = "grey55"), 
        axis.title = element_text(size=14, color = "grey55"),
        legend.position = 'none')
ggsave('Documents/pca_group_ids_preliminary.png')
autoplot(cbecs_pca, data = cbecs_clean_df, loadings=TRUE, loadings.label = TRUE, alpha=0.2, loadings.label.size = 3) +
  ggtitle('Principal Component Analysis - Vectors') +
  theme(plot.title = element_text(hjust = 0.5, size=20),
        strip.text = element_text(size = 20),
        plot.background = element_rect(fill = "lightgrey"), 
        panel.background = element_rect(fill = "white"), 
        panel.grid.major.x = element_line(color = "lightgrey"), 
        panel.grid.major.y = element_line(color = "lightgrey"), 
        axis.text = element_text(size=10, color = "grey55"), 
        axis.title = element_text(size=14, color = "grey55"))
ggsave('Documents/pca_group_vectors_preliminary.png')
```


#Remove collinear, and other possible response variable, columns and create df for prediction for just electricity
```{r}
elbtu_pred_list <- append(
  removed_response_list,
  'ELBTUPerSf')
cbecs_elbtu_df <- cbecs_clean_df %>% 
  select_(.dots = elbtu_pred_list) %>% 
  na.omit()
```

```{r}
#split train/test

```

#Random Forest
```{r fig.height=10}
cbecs_pbaplus_df <- cbecs_clean_df %>% 
  select(-PBA) %>% 
  select(one_of(removed_response_list))
cbecs_pbaplus_rf <- randomForest(PBAPLUS ~ ., 
                              data = cbecs_pbaplus_df,
                              ntree = 100,
                              maxnodes = 100
                  )
varImpPlot(cbecs_pbaplus_rf)

#set up training/tuning parameters - examples in caret - https://machinelearningmastery.com/tune-machine-learning-algorithms-in-r/
```

```{r fig.width=30}
tree_func(cbecs_pbaplus_rf, 1)
```


```{r fig.height=10}

tst <- cbecs_pbaplus_df %>% bind_cols(PBAPLUSPred = predict(cbecs_pbaplus_rf, newdata=cbecs_pbaplus_df))
ggplot(tst, aes(PBAPLUSPred, ..count..)) + geom_bar() + facet_wrap(~PBAPLUS, scales = "free")
data.frame(error = cbecs_pbaplus_rf$confusion[,'class.error']) %>% add_rownames(var="PBAPLUS") %>% arrange(desc(error))
```

#svm
```{r eval=FALSE}
#Takes a long time, only run when needed
svm_fit <- svm(PBA ~ ., 
               data = cbind(cbecs_clean_df[, cbecs_clean_numeric_cols], PBA = cbecs_clean_df$PBA), 
               kernel='linear', 
               cost=10, 
               scale=FALSE, 
               cachesize=2000)
plot(svm_fit, data = cbecs_clean_df, ELBTUPerSf ~ CDD65)
plot(svm_fit, data = cbecs_clean_df, log(NGBTUPerSf + 1) ~ HDD65)
```