---
title: "cbecs_electrical_analysis"
author: "John Grando"
date: "February 11, 2019"
output: html_document
---

Source files
```{r}
source('RScripts/elbtu_base_training_psf.R')
```

Libraries
```{r}
library(aws.s3)
library(aws.signature)
library(kableExtra)
library(factoextra)
```

#ploting funcitons
```{r}
source('RScripts/cbecs_common_functions.R')
#Set number of most important variables to take from each model
top_n_rows <- 10
```

Response Variable
```{r}
ggplot(cbecs_el_cleaned_df, aes(x=ELBTUPerSf)) + 
  geom_density()
#lmbda <- BoxCoxTrans(cbecs_el_cleaned_df$ELBTU + 1)$lambda
lmbda <- 0
if(lmbda!=0){
  ggplot(cbecs_el_cleaned_df, aes(x=ELBTUPerSf^lmbda)) + 
    geom_density() + 
    stat_function(fun=dnorm,
                color="blue",
                args=list(
                  mean=mean(cbecs_dfs$clean_df$ELBTUPerSf^lmbda, na.rm = TRUE),
                  sd(cbecs_dfs$clean_df$ELBTUPerSf^lmbda, na.rm = TRUE)
                )
    ) +
    ggtitle(paste('ELBTU Transformed via BoxCox, Lambda = ', lmbda, sep="")) +
    theme(axis.text.x = element_text(angle=60, hjust=1),
          plot.title = element_text(hjust = 0.5,  size=16),
          plot.background = element_rect(fill = "lightgrey"), 
          panel.background = element_rect(fill = "white"), 
          panel.grid.major.x = element_line(color = "lightgrey"), 
          panel.grid.major.y = element_line(color = "lightgrey"),
          axis.text = element_text(size=12, color = "grey55"), 
          axis.title = element_text(size=12, color = "grey55"), 
          legend.title=element_text(size=7),
          legend.text=element_text(size=6),
          legend.key.height = unit(0.5, "cm"),
          title = element_text(size=14, color = "grey55"))
}
if(lmbda==0){
  ggplot(cbecs_el_cleaned_df, aes(x=log(ELBTUPerSf+1))) + 
    geom_density() + 
    stat_function(fun=dnorm,
                color="blue",
                args=list(
                  mean=mean(log(cbecs_dfs$clean_df$ELBTUPerSf+1), na.rm = TRUE),
                  sd(log(cbecs_dfs$clean_df$ELBTUPerSf+1), na.rm = TRUE)
                )
    ) +
    ggtitle(paste('ELBTUPerSf Transformed via BoxCox, Lambda = ', lmbda, sep="")) +
    theme(axis.text.x = element_text(angle=60, hjust=1),
          plot.title = element_text(hjust = 0.5,  size=16),
          plot.background = element_rect(fill = "lightgrey"), 
          panel.background = element_rect(fill = "white"), 
          panel.grid.major.x = element_line(color = "lightgrey"), 
          panel.grid.major.y = element_line(color = "lightgrey"),
          axis.text = element_text(size=12, color = "grey55"), 
          axis.title = element_text(size=12, color = "grey55"), 
          legend.title=element_text(size=7),
          legend.text=element_text(size=6),
          legend.key.height = unit(0.5, "cm"),
          title = element_text(size=14, color = "grey55"))
}
ggsave('Documents/Images/electricity_psf_response.png', width = 8, height = 4, units = 'in')
#Reset to 1, not going to use it.
lmbda <- 1
```

#PCA
```{r}
set.seed(20)
s3load('ModelSaves/elbtu_pca_psf.RData', bucket = 'cuny-msds-final-project-cbecs')
p1 <- fviz_eig(cbecs_pca, addlabels = TRUE)
var <- get_pca_var(cbecs_pca)
p2 <- fviz_pca_var(cbecs_pca, select.var = list(contrib=20), repel = TRUE)
p3 <- fviz_contrib(cbecs_pca, choice = "var", axes = 1:20, top = 20)
pca_imp_df <- fviz_contrib(cbecs_pca, choice = "var", axes = 1:20, top = 50)$data %>% 
  arrange(desc(contrib)) %>% 
  head(top_n_rows) %>% 
  #select(name) %>% 
  rename(feature = name) %>% 
  mutate(feature = as.character(feature)) %>% 
  rename(Overall = contrib) %>% 
  #convert to percentages
  mutate(Overall = 100 * Overall)
grid.arrange(p1, p3, nrow=2)
g <- arrangeGrob(p1, p3, nrow = 2)
ggsave('Documents/Images/electricity_psf_pca_vars.png', g, width = 7.5, height = 5, units = 'in')
```

#PLS 
```{r}
set.seed(20)
s3load('ModelSaves/elbtu_pls_psf.RData', bucket = 'cuny-msds-final-project-cbecs')
print(pls_train)
varImp(pls_train)
pls_plot <- plot_fun(in_model=pls_train, 
                     n_features=top_n_rows, 
                     short_name='pls', 
                     alt_predict = TRUE, 
                     log_tran = TRUE,
                     observed_df = cbecs_elbtu_encoded_center_scale_test_df,
                     response = cbecs_elbtu_encoded_center_scale_test_df$ELBTUPerSf,
                     fuel_type = 'electricity_psf',
                     area_vector = cbecs_dfs$clean_df$SQFT[-cbecs_train_list])
pls_plot$vars_plot
pls_plot$pvo_plot
plot(pls_plot$tmp_model)
pls_imp_df <- pls_plot$imp_df
pls_plot$RMSE
pls_plot$R2
pls_plot$RMSE_total
pls_plot$R2_total
#View(t(cbecs_el_cleaned_df %>% tibble::rownames_to_column() %>% mutate(pred = exp(predict(pls_train, newdata = cbecs_elbtu_encoded_center_scale_df))) %>% filter(rowname==406|rowname==4974) %>% select(ELBTU, pred, SQFTC, RFGVEN, RFGICE, RFGWI, EMCS, GENUSE, one_of(pls_imp_df$feature))))

#View(t(cbecs_elbtu_encoded_center_scale_df %>% tibble::rownames_to_column() %>% mutate(pred = exp(predict(pls_train, newdata = cbecs_elbtu_encoded_center_scale_df))) %>% filter(rowname==406|rowname==4974) %>% select(ELBTU, pred, one_of(pls_imp_df$feature))))
```

#Tree regression importance
```{r fig.height=10}
set.seed(20)
s3load('ModelSaves/elbtu_rf_psf.RData', bucket = 'cuny-msds-final-project-cbecs')
print(rf_train)
varImp(rf_train)
rf_plot <- plot_fun(in_model=rf_train, 
                    n_features=top_n_rows, 
                    short_name='rf', 
                    log_tran = FALSE, 
                    alt_predict = FALSE,
                    observed_df = cbecs_elbtu_encoded_center_scale_test_df,
                    response = cbecs_elbtu_encoded_center_scale_test_df$ELBTUPerSf,
                    fuel_type = 'electricity_psf',
                    area_vector = cbecs_dfs$clean_df$SQFT[-cbecs_train_list])
rf_plot$vars_plot
rf_plot$pvo_plot
plot(rf_plot$tmp_model)
rf_imp_df <- rf_plot$imp_df
rf_plot$RMSE
rf_plot$R2
#how to evaluate rows
#View(t(cbecs_el_cleaned_df %>% tibble::rownames_to_column() %>% mutate(pred = predict(rf_train, newdata = cbecs_elbtu_encoded_center_scale_df)) %>% filter(rowname==507|rowname==406|rowname==4974)))
#View(t(cbecs_elbtu_encoded_center_scale_df %>% tibble::rownames_to_column() %>% mutate(pred = predict(rf_train, newdata = cbecs_elbtu_encoded_center_scale_df)) %>% filter(rowname==507|rowname==406|rowname==4974) %>% select(ELBTU, pred, one_of(rf_imp_df$feature))))
```

lasso
```{r eval=FALSE}
set.seed(20)
s3load('ModelSaves/elbtu_l_psf.RData', bucket = 'cuny-msds-final-project-cbecs')
print(l_train)
varImp(l_train)
l_plot <- plot_fun(in_model=l_train, 
                   n_features=top_n_rows, 
                   short_name='l', 
                   alt_predict = TRUE, 
                   log_tran = FALSE,
                   observed_df = cbecs_elbtu_encoded_center_scale_test_df,
                   response = cbecs_elbtu_encoded_center_scale_test_df$ELBTUPerSf,
                   fuel_type = 'electricity_psf',
                   area_vector = cbecs_dfs$clean_df$SQFT[-cbecs_train_list])
l_plot$vars_plot
l_plot$pvo_plot
plot(l_plot$tmp_model)
l_imp_df <- l_plot$imp_df %>% mutate(Overall = 100 * Overall)
l_plot$RMSE
l_plot$R2
l_plot$MAE
```

leaps
```{r}
set.seed(20)
s3load('ModelSaves/elbtu_lp_psf.RData', bucket = 'cuny-msds-final-project-cbecs')
print(lp_train)
varImp(lp_train)
lp_plot <- plot_fun(in_model=lp_train, 
                    n_features=top_n_rows, 
                    short_name='lp', 
                    alt_predict = TRUE, 
                    log_tran = FALSE,
                    observed_df = cbecs_elbtu_encoded_center_scale_test_df,
                    response = cbecs_elbtu_encoded_center_scale_test_df$ELBTUPerSf,
                    fuel_type = 'electricity_psf',
                    area_vector = cbecs_dfs$clean_df$SQFT[-cbecs_train_list])
lp_plot$vars_plot
lp_plot$pvo_plot
plot(lp_plot$tmp_model)
lp_imp_df <- lp_plot$imp_df %>% mutate(Overall = 100 * Overall) %>% filter(!is.na(Overall))
lp_plot$RMSE
lp_plot$R2
```

#recursive feaure extraction
```{r}
set.seed(20)
s3load('ModelSaves/elbtu_rfe_psf.RData', bucket = 'cuny-msds-final-project-cbecs')
rfe_train
plot(rfe_train, type=c('g', 'o'))
rfe_imp_df <- rfe_train$variables %>% 
  filter(Variables == top_n_rows) %>%
  group_by(var) %>% 
  summarize(Overall = mean(Overall)) %>% 
  mutate(Overall = Overall / max(Overall) * 100) %>% 
  arrange(desc(Overall)) %>% 
  select(var, Overall) %>% 
  rename(feature = var)
rfe_plot <- plot_pred_obs(in_model_sub = rfe_train, 
                          short_name_sub = 'rfe',
                          alt_predict_sub = TRUE, 
                          log_tran_sub = FALSE,
                          observed_df = cbecs_elbtu_encoded_center_scale_test_df,
                          response = cbecs_elbtu_encoded_center_scale_test_df$ELBTUPerSf,
                          fuel_type_sub = 'electricity_psf',
                          area_vector = cbecs_dfs$clean_df$SQFT[-cbecs_train_list])

varImp(rfe_train)
rfe_plot$p
plot(rfe_plot$tmp_mdl)
rfe_plot$RMSE_untransformed
rfe_plot$R2_untransformed

#specific graph needs to be made
p_rfe <- ggplot(data = data.frame(varImp(rfe_train) %>% 
                                    tibble::rownames_to_column(var='feature') %>% 
                                    arrange(desc(Overall)) %>% 
                                    head(top_n_rows)), aes(x=reorder(feature, desc(Overall)), y=Overall)) + 
    geom_bar(stat='identity') +
    ggtitle('Variable Importance') +
    labs(x='Feature') +
    theme(axis.text.x = element_text(angle=60, hjust=1),
          plot.title = element_text(hjust = 0.5,  size=16),
          plot.background = element_rect(fill = "lightgrey"), 
          panel.background = element_rect(fill = "white"), 
          panel.grid.major.x = element_line(color = "lightgrey"), 
          panel.grid.major.y = element_line(color = "lightgrey"),
          axis.text = element_text(size=12, color = "grey55"), 
          axis.title = element_text(size=12, color = "grey55"), 
          legend.title=element_text(size=7),
          legend.text=element_text(size=6),
          legend.key.height = unit(0.5, "cm"),
          title = element_text(size=14, color = "grey55"))
ggsave(paste0('Documents/Images/electricity_psf_rfe_vars.png'), p_rfe, width = 8, height = 4, units = 'in')
p_rfe
```


#Simple neural network training
```{r echo=FALSE, fig.width=10}
set.seed(20)
s3load('ModelSaves/elbtu_nn_psf.RData', bucket = 'cuny-msds-final-project-cbecs')
print(nn_train)
varImp(nn_train)
nn_plot <- plot_fun(in_model=nn_train, 
                    n_features=top_n_rows, 
                    short_name='nn', 
                    alt_predict = TRUE,
                    log_tran = FALSE,
                    observed_df = cbecs_elbtu_encoded_center_scale_test_df,
                    response = cbecs_elbtu_encoded_center_scale_test_df$ELBTUPerSf,
                    fuel_type = 'electricity_psf',
                    area_vector = cbecs_dfs$clean_df$SQFT[-cbecs_train_list])
nn_plot$vars_plot
nn_plot$pvo_plot
plot(nn_plot$tmp_model)
nn_imp_df <- nn_plot$imp_df %>% mutate(Overall = 100 * Overall)
nn_plot$RMSE
nn_plot$R2
```

#load models, again if not done before
```{r eval=FALSE}
s3load('ModelSaves/elbtu_pca.RData', bucket = 'cuny-msds-final-project')
s3load('ModelSaves/elbtu_pls.RData', bucket = 'cuny-msds-final-project')
s3load('ModelSaves/elbtu_rf.RData', bucket = 'cuny-msds-final-project')
s3load('ModelSaves/elbtu_l.RData', bucket = 'cuny-msds-final-project')
s3load('ModelSaves/elbtu_lp.RData', bucket = 'cuny-msds-final-project')
s3load('ModelSaves/elbtu_rfe.RData', bucket = 'cuny-msds-final-project')
s3load('ModelSaves/elbtu_nn.RData', bucket = 'cuny-msds-final-project')
```

#trained model summaries
```{r}
resamps <- resamples(list(
  pls_fit = pls_train,
  rf_fit = rf_train,
  #l_fit = l_train,
  lp_fit = lp_train,
  rfe_fit = rfe_train,
  nn_fit = nn_train
))
summary(resamps)

manual_summary <- data.frame(
  Model = c('partialLeastSquares', 
            'randomForest', 
            #'lasso', 
            'leaps', 
            'recursiveFeatureExtraction', 
            'neuralNetwork'),
  RMSE = c(pls_plot$RMSE, 
           rf_plot$RMSE, 
           #l_plot$RMSE, 
           lp_plot$RMSE, 
           rfe_plot$RMSE_untransformed, 
           nn_plot$RMSE),
  R2 = c(pls_plot$R2, 
         rf_plot$R2, 
         #l_plot$R2, 
         lp_plot$R2, 
         rfe_plot$R2_untransformed, 
         nn_plot$R2),
  MAE = c(pls_plot$MAE, 
          rf_plot$MAE, 
          #l_plot$MAE, 
          lp_plot$MAE, 
          rfe_plot$MAE_untransformed, 
          nn_plot$MAE),
  MAPE = c(pls_plot$MAPE, 
          rf_plot$MAPE, 
          #l_plot$MAPE, 
          lp_plot$MAPE, 
          rfe_plot$MAPE_untransformed, 
          nn_plot$MAPE),
  RMSE_total = c(pls_plot$RMSE_total, 
           rf_plot$RMSE_total, 
           #l_plot$RMSE_total, 
           lp_plot$RMSE_total, 
           rfe_plot$RMSE_total_untransformed, 
           nn_plot$RMSE_total),
  R2_total = c(pls_plot$R2_total, 
         rf_plot$R2_total, 
         #l_plot$R2_total, 
         lp_plot$R2_total, 
         rfe_plot$R2_total_untransformed, 
         nn_plot$R2_total),
  MAE_total = c(pls_plot$MAE_total, 
          rf_plot$MAE_total, 
          #l_plot$MAE_total, 
          lp_plot$MAE_total, 
          rfe_plot$MAE_total, 
          nn_plot$MAE_total),
  MAPE_total = c(pls_plot$MAPE_total, 
          rf_plot$MAPE_total, 
          #l_plot$MAPE_total, 
          lp_plot$MAPE_total, 
          rfe_plot$MAPE_total_untransformed, 
          nn_plot$MAPE_total)
)

p <- manual_summary %>% 
  arrange(MAPE) %>% 
  select(-matches('.*_total')) %>%
  kable('html', 
        caption = 'Feature Extraction Model Results') %>% 
  kable_styling()
p
```

#Save dataframes for full analysis
```{r}
nn_input_df <- cbecs_elbtu_encoded_center_scale_df %>% 
  select(one_of(pls_imp_df$feature), 
         one_of(pca_imp_df$feature),
         one_of(rf_imp_df$feature),
         #one_of(l_imp_df$feature),
         one_of(lp_imp_df$feature),
         one_of(nn_imp_df$feature),
         one_of(rfe_imp_df$feature),
         ELBTUPerSf
         #one_of(colnames(cbecs_elbtu_encoded_center_scale_df %>% select(matches('^PBAPLUS'))))
  )

nn_input_pba_labels <- cbecs_el_cleaned_df$PBAPLUS

variable_by_importance_df <- data.frame(rbind(
  pca_imp_df, 
  pls_imp_df, 
  rf_imp_df, 
  lp_imp_df, 
  nn_imp_df, 
  rfe_imp_df, 
  nn_imp_df)) %>% 
    filter(!is.na(Overall)) %>% 
    group_by(feature) %>% 
    summarize(Overall = sum(Overall)) %>% 
    ungroup() %>% 
    mutate(Overall = Overall / max(Overall) * 100) %>% 
    arrange(desc(Overall))

variables_by_importance <- variable_by_importance_df  %>% 
  pull(feature)

numeric_cols <- cbecs_dfs$encoded_numeric_cols
non_numeric_cols <- cbecs_dfs$encoded_non_numeric_cols
sqft_values <- cbecs_el_cleaned_df$SQFT

nn_input_data_name <- 'ModelSaves/elbtu_nn_input_psf.RData'

save(nn_input_pba_labels, 
     nn_input_df, 
     elbtu_pre_process,
     cbecs_elbtu_encoded_center_scale_df,
     variables_by_importance,
     numeric_cols,
     non_numeric_cols,
     manual_summary,
     sqft_values,
     file= nn_input_data_name
)
put_object(file = nn_input_data_name, 
           bucket = 'cuny-msds-final-project-cbecs', 
           object = nn_input_data_name)

#total variable plot
p_all_v <- ggplot(data = variable_by_importance_df %>% head(20), 
                aes(x=reorder(feature, desc(Overall)), 
                    y=Overall)) + 
    geom_bar(stat='identity') +
    ggtitle('Variable Importance') +
    labs(x='Feature') +
    theme(axis.text.x = element_text(angle=60, hjust=1),
          plot.title = element_text(hjust = 0.5,  size=16),
          plot.background = element_rect(fill = "lightgrey"), 
          panel.background = element_rect(fill = "white"), 
          panel.grid.major.x = element_line(color = "lightgrey"), 
          panel.grid.major.y = element_line(color = "lightgrey"),
          axis.text = element_text(size=12, color = "grey55"), 
          axis.title = element_text(size=12, color = "grey55"), 
          legend.title=element_text(size=7),
          legend.text=element_text(size=6),
          legend.key.height = unit(0.5, "cm"),
          title = element_text(size=14, color = "grey55"))
ggsave(paste0('Documents/Images/electricity_psf_all_vars.png'), p_all_v, width = 8, height = 4, units = 'in')
p_all_v
```

#Plot selected variables
```{r}
vars <- variables_by_importance[1:21]
iter <- 0
for(i in vars){
  plot_vars(cbecs_dfs$encoded_df, 
            cbecs_dfs$encoded_df$ELBTU, 
            'electricity_psf', 
            i, 
            iter,
            'original',
            'Untransformed',
            'Electricity')
  iter <- iter + 1
}
iter <- 0
for(i in vars){
  plot_vars(cbecs_elbtu_encoded_center_scale_df, 
            log(cbecs_elbtu_encoded_center_scale_df$ELBTU), 
            'electricity_psf', 
            i, 
            iter,
            'transformed',
            'Transformed',
            'Logscale Electricity')
  iter <- iter + 1
}
```

